version: '3'

services:
  py01_docker_rest_api:
    container_name: py01_docker_rest_api
    build: .
    environment:
      # tus variables de entorno
    ports:
      - "5002:5000"
    depends_on:
      - python_database
      - mongo
      - spark-master
      - spark-worker
      - neo4j
    networks:
      - web
    command: spark-submit /app/spark_jobs/process_responses.py

  python_database:
    container_name: python_database
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - web
    volumes:
      - ./src/data/:/docker-entrypoint-initdb.d/

  mongo:
    container_name: mongo
    image: mongo:7.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: wandertulojimenez
      MONGO_INITDB_ROOT_PASSWORD: Esy9UlXjfIoBVn7v
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - web

  redis:
    container_name: redis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    networks:
      - web

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - web

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - web

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  mongo_data:
