version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - web

  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_INTERNAL://kafka-broker-1:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - web

  py01_docker_rest_api:
    container_name: py01_docker_rest_api
    build: .
    environment:
      KAFKA_BROKER_URL: kafka-broker-1:9092
      SECRET_KEY: B!1w8*NAt1T^%kvhUI*s^
      JWT_KEY: D5*F?_1?-d$f*1
      DATABASE_HOST: python_database
      DATABASE_NAME: surveys
      DATABASE_USER: postgres
      DATABASE_PASSWORD: mysecretpassword
      DATABASE_PORT: "5432"
      MONGO_INITDB_ROOT_USERNAME: wandertulojimenez
      MONGO_INITDB_ROOT_PASSWORD: Esy9UlXjfIoBVn7v
      MONGO_DATABASE_HOST: mongo
      MONGO_DATABASE_PORT: 27017
      MONGO_DATABASE_NAME: ProyectoBases2
      MONGO_COLLECTION_NAME: surveys
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - "5002:5000"
    depends_on:
      - kafka-broker-1
      - python_database
      - mongo
      - spark-master
      - spark-worker
      - neo4j
    networks:
      - web
    command: spark-submit /app/spark_jobs/process_responses.py

  python_database:
    container_name: python_database
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - web
    volumes:
      - ./src/data/:/docker-entrypoint-initdb.d/

  mongo:
    container_name: mongo
    image: mongo:7.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: wandertulojimenez
      MONGO_INITDB_ROOT_PASSWORD: Esy9UlXjfIoBVn7v
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - web

  redis:
    container_name: redis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    networks:
      - web
  
  kafka_consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - kafka-broker-1
      - zookeeper

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - web

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - web

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  mongo_data:
